create table if not exists public.saved_locations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  city text not null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, latitude, longitude)
);

alter table public.saved_locations enable row level security;

drop policy if exists "Users can read their own saved locations" on public.saved_locations;
create policy "Users can read their own saved locations"
on public.saved_locations for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own saved locations" on public.saved_locations;
create policy "Users can insert their own saved locations"
on public.saved_locations for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own saved locations" on public.saved_locations;
create policy "Users can update their own saved locations"
on public.saved_locations for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own saved locations" on public.saved_locations;
create policy "Users can delete their own saved locations"
on public.saved_locations for delete
to authenticated
using ((select auth.uid()) = user_id);
